# cluster commands
cluster: 
  mkdir -p logs/cluster_logs/`date +"%Y%m%d"`/{rule} &&
  sbatch 
    --job-name={rule}
    --output=logs/cluster_logs/`date +"%Y%m%d"`/{rule}/%j.out
    --partition={resources.partition}
    --account=pschloss0
    --nodes=1
    --time=100:00:00
    --mem=8000
    --cpus-per-task=8

#    --mem={resources.mem_mb}
#    --cpus-per-task={threads}

# default resources used for rules with no Resources specified
default-resources: 
  - threads=1
  - mem_mb=4000
  - partition=standard
  - time_min=120
  - job_name="sing"
  
# snakemake args
jobs: 3000
scheduler: "greedy"
rerun-incomplete: true
use-conda: true
conda-frontend: "mamba"
keep-going: true
latency-wait: 120
touch: false
conda-cleanup-envs: false
conda-create-envs-only: false
group-components:
  - prune_pc=1000
  - prune_otu=1000
  - alpha=1000
  - beta=1000
  - amova=1000
